Various fixes for failures with -Wall
xmonad/xmonad-extras pull request #19
Opened 2018-12-16 13:11 UTC by mdorman

I'm not going to suggest that any of these are necessarily the best way to handle these changes---their sole virtue is that they work.  I'm happy to try and handle things in better ways if people have specific feedback (except for the Storable thing---that's outta my depth).

2018-12-17 05:00 UTC, psibi commented
@mdorman The CI seems to be failing.

2018-12-19 13:51 UTC, peti requested changes

2018-12-19 13:51 UTC, peti commented on xmonad-extras.cabal
> +        build-depends: alsa-mixer >= 0.3
You need to make the same change in `stack.yaml` to fix the continuous build on Travis-CI.

2018-12-22 10:18 UTC, merged

2018-12-22 10:19 UTC, psibi commented
Released 0.15.1 to address the issue.